jitterbunk/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('powerups/', include('powerups.urls')),
    path('admin/', admin.site.urls),
]

powerups/urls.py
from django.urls import path

from . import views

app_name = 'powerups'
urlpatterns = [
    path('', views.index, name='index'),
    path('all/<str:order>/', views.AllPowerupsView.as_view(), name='all'),
    path('sort', views.sort, name='sort'),
    path('users/', views.AllUsersView.as_view(), name='users'),
    path('users/<int:pk>/', views.user_detail, name='user_detail'),
    path('<int:pk>/', views.PowerUpDetailView.as_view(), name='powerup_detail'),
    path('add_powerup', views.addPowerup, name='add_powerup'),
    path('create', views.create, name='create')
]

powerups/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=200)
    photo = models.CharField(max_length=200)
    team = models.CharField(max_length=200)

    def __str__(self):
        return self.username
    

class Powerup(models.Model):
    title = models.CharField(max_length=200)
    link = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    date_added = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    team = models.CharField(max_length=200)
    
    def __str__(self):
        return self.title

powerups/views.py
from django.shortcuts import get_object_or_404, render

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone


from .models import Powerup, User

# Create your views here.
def index(request):
    return render(request, 'powerups/index.html')

class AllPowerupsView(generic.ListView):

    template_name = 'powerups/all.html'
    context_object_name = 'all_powerups_list'

    def get_queryset(self):
        """
        Return all the powerups (not including those set in the future)
        """
        order = self.kwargs["order"]

        return Powerup.objects.filter(
            date_added__lte=timezone.now()
        ).order_by(order)
        
def sort(request):
    sort_by = request.GET['sort_by']

    return HttpResponseRedirect(reverse('powerups:all', kwargs={'order' : sort_by}))

class AllUsersView(generic.ListView):

    template_name = 'powerups/all_user.html'
    context_object_name = 'all_users_list'

    def get_queryset(self):
        """
        Return all users
        """
        return User.objects.all()

def user_detail(request, pk):
    powerup_list = Powerup.objects.filter(user__pk=pk)
    user = User.objects.filter(id=pk)[0]
    context = {
        'user': user,
        'powerup_list': powerup_list
        }
    return render(request, 'powerups/user_detail.html', context)

class PowerUpDetailView(generic.DetailView):
    model = Powerup
    template_name = 'powerups/powerup_detail.html'

def addPowerup(request):
    user_list = User.objects.all()
    return render(request, 'powerups/add_powerup.html', {'user_list': user_list})

def create(request):
    title = request.POST['title']
    link = request.POST['link']
    description = request.POST['description']
    date_added = timezone.now()
    user = request.POST['user']
    team = request.POST['team']

    try:
        user = User.objects.get(username = user)
    except (KeyError, User.DoesNotExist):
        print('User does not exist')
        user_list = User.objects.all()
        return render(request, 'powerups/add_powerup.html', {
            'user_list': user_list,
            'error_message': "User doesn't exist.",
            'old_form_entries': {
                'title': title,
                'link': link,
                'description': description,
                'team': team
            },
        })
    
    new_powerup = Powerup(title=title, link=link, description=description, date_added=date_added, user=user, team=team)
    new_powerup.save()

    return HttpResponseRedirect(reverse('powerups:index'))


'''
class UserView(generic.ListView):
    model = User
    template_name = 'powerups/user_detail.html'

    def get_queryset(self):
        return User.objects.all()
        
def user_powerups(request, user_id):
    user = get_object_or_404(User, pk=user_id)

    powerup = user.powerup_set.get(pk=request.GET['powerup'])

    return HttpResponseRedirect(reverse('powerups:results', args=(question.id,)))

    try:
        powerup = user.powerup_set.get(pk=request.GET['powerup'])
    except (KeyError, Powerup.DoesNotExist):
        return render(request, 'powerups/user_detail.html', {
            'user': user,
            'error_message': "No powerups.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
'''

powerups/templates/powerups/add_powerup.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'powerups/style.css' %}">

<form action="{% url 'powerups:create' %}" method="post">
{% csrf_token %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <label for="title">Title:</label><br>
    <input type="text" id="title" name="title" value="{% if old_form_entries %} {{old_form_entries.title}} {% endif %}"><br>

    <label for="link">Link:</label><br>
    <input type="url" id="link" name="link" value="{% if old_form_entries %} {{old_form_entries.link}} {% endif %}"><br>

    <label for="description">Description:</label><br>
    <input type="text" id="description" name="description" value="{% if old_form_entries %} {{old_form_entries.description}} {% endif %}"><br>

    <label for="user">User:</label><br>
    <!-- <input type="text" id="user" name="user"><br> -->
    <select id="user" name="user">
        {% for user in user_list %}
            <option value="{{user.username}}">{{user.username}}</option>
        {% endfor %}
    </select>
    <br>

    <label for="team">Team:</label><br>
    <input type="text" id="team" name="team" value="{% if old_form_entries %} {{old_form_entries.team}} {% endif %}"><br>

<input type="submit" value="Create">
</form>

<br>
<p><a href="{% url 'powerups:index' %}">Go to Home</a></p>

powerups/templates/powerups/all.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'powerups/style.css' %}">

<h1>All Powerups List</h1>

<form action="{% url 'powerups:sort' %}" method="get">
    {% csrf_token %}
    <select id="sort_by" name="sort_by">
        <option value="date_added">Date</option>
        <option value="title">Title</option>
    </select>
    <input type="submit" value="Sort">
</form>

{% if all_powerups_list %}
    <ul>
    {% for powerup in all_powerups_list %}
        <li><a href="{% url 'powerups:powerup_detail' powerup.id %}">{{ powerup.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No powerups are available.</p>
{% endif %}

<br>
<p><a href="{% url 'powerups:index' %}">Go to Home</a></p>

powerups/templates/powerups/all_user.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'powerups/style.css' %}">

<h1>All Users List</h1>

{% if all_users_list %}
    <ul>
    {% for user in all_users_list %}
        <li><a href="{% url 'powerups:user_detail' user.id %}">{{ user.username }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No users are available.</p>
{% endif %}

<br>
<p><a href="{% url 'powerups:index' %}">Go to Home</a></p>

powerups/templates/powerups/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'powerups/style.css' %}">

<h1>Home</h1>

<p>
<a href="{% url 'powerups:all' 'id' %}">View all powerups</a> <br>
<a href="{% url 'powerups:users' %}"> View all users</a> <br>
<a href="{% url 'powerups:add_powerup' %}">Add a new powerup</a>
</p>

powerups/templates/powerups/powerup_detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'powerups/style.css' %}">

<a href="{{ powerup.link}}"><h1>{{ powerup.title }}</h1></a>
<h2>Description: </h2>
<p>{{ powerup.description }}</p>

<br>
<ul>
    <li>Date Added: {{ powerup.date_added }}</li>
    <li>User: {{ powerup.user }}</li>
    <li>Team: {{ powerup.team }}</li>
</ul>

<br>
<p><a href="{% url 'powerups:index' %}">Go to Home</a></p>

powerups/templates/powerups/user_detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'powerups/style.css' %}">

{% if user %}
    <h1>{{ user.username }}</h1>
    {% with 'powerups/images/'|add:user.photo as user_photo %}
        <img src="{% static user_photo %}">
    {% endwith %}
    
    <p>Team: {{ user.team }}</p>
    <br>
    <p>Personal Powerups:</p>
    <ul>
    {% for powerup in powerup_list.all %}
        <li><a href="{% url 'powerups:powerup_detail' powerup.id %}">{{powerup.title}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p> No user</p>
{% endif %}

<br>
<p><a href="{% url 'powerups:index' %}">Go to Home</a></p>